version: "3.2"
services:

  sql-server-db:
    container_name: dev-environment-mssql-server
    image: microsoft/mssql-server-linux:latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "agoda1234"
      ACCEPT_EULA: "Y"